### ISSUE TITLE
410 Gone error for get videolist

### ISSUE THREAD

**Issue by faisalike** [skitsanosinc/vzaar-api-net#2]
var query = new VideoListQuery
{
	count = 10,
	page = 1
};

var list = api.getVideoList(query);
Exception:
The remote server returned an error: (410) Gone.

**Comment by skitsanos** [comment]
@faisalike Please refer to the new api lib at [https://github.com/vzaar/vzaar-api-net](https://github.com/vzaar/vzaar-api-net) Most likely vzaar changed API endpoints now and my library is deprecated for some time.
